export { atoms, getAtomById, getChildAtoms, getAtomsForTask } from './atoms'
export type { Atom, AtomizedWord, UserAtomProgress } from './atoms'

// Lazy-loaded atomized words (generated by scripts/parse-atomization.cjs)
let _atomizedWords: import('./atoms').AtomizedWord[] | null = null

export async function getAtomizedWords(): Promise<import('./atoms').AtomizedWord[]> {
  if (_atomizedWords) return _atomizedWords
  const data = await import('./atomizedWords.json')
  _atomizedWords = (data.words || []).map((w: any) => {
    const raw = w.rawForm || ''
    const dots = (raw.match(/\./g) || []).length
    let questionText = 'Вопрос:'
    if (w.taskNumber === 4) {
      questionText = 'Как правильно?'
    } else if (w.taskNumber === 5) {
      questionText = 'Выберите правильное слово:'
    } else if (dots > 0) {
      questionText = dots === 1 ? 'Вставьте пропущенную букву:' : 'Вставьте пропущенные буквы:'
    } else {
      questionText = 'Как правильно?'
    }
    return {
      ...w,
      difficulty: w.difficulty as 'easy' | 'medium' | 'hard',
      questionText,
    }
  })
  return _atomizedWords
}

export function getQuestionsForAtom(
  atomId: string,
  words: import('./atoms').AtomizedWord[],
  limit = 10
): import('./atoms').AtomizedWord[] {
  return words
    .filter(w => w.atoms.includes(atomId))
    .slice(0, limit)
}

export function getWeakAtoms(
  progress: Record<string, import('./atoms').UserAtomProgress>,
  threshold = 70
): string[] {
  return Object.values(progress)
    .filter(p => p.accuracy > 0 && p.accuracy < threshold)
    .sort((a, b) => a.accuracy - b.accuracy)
    .map(p => p.atomId)
}
